server:
  port: 8080

spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update # (1) ??? ?? ??  update -> create 변ㄱ
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    database: mysql

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

token:
  expiration_time: 86400000
  secret: sodlgjkfigjkijsekifhdufgyjkzejfkhslf234567890987654sdgfgnhgjkhdfsgafsdxgcdhjfkgchlv364785960584736sdfguhdhsijsopfj
